### ISSUE TITLE
[Bug] Can't put spaces into any of the input boxes (name, chat, etc.) 

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/cavatars-game#3]
These two boxes, for example: 

![Screenshot_4](https://user-images.githubusercontent.com/13829168/103841252-bccfa100-5058-11eb-8091-b8ba8594fa12.png)

I don't really mind that player names don't have spaces, but would like folks to be able to make spaces in chat.

**Comment by Abdelilah-Majid** [comment]
can you explain more what is the problem exactly

**Comment by Abdelilah-Majid** [comment]
i will try to fix that

**Comment by Abdelilah-Majid** [comment]
oh! sorry i forgot i have some work to do
sorry i wanted to work on your game but i have somethings to do

**Comment by rfaile313** [comment]
If you build the program and run it you'll see that you can't put spaces in any of the text input boxes, that is the bug.

**Comment by rfaile313** [comment]
This is fixed. I found out you can't access these properties directly and need to use the built in functions from phaser due to getters/setters and actually removing/adding event listeners. 

Specifically, calling `disableGlobalCapture()` and `enableGlobalCapture()`

Solution:

```js
  const chatBox = document.getElementById("chat");
  chatBox.addEventListener("focus", () => {this.input.keyboard.disableGlobalCapture()});
  chatBox.addEventListener("blur", () =>  {this.input.keyboard.enableGlobalCapture()});
  ```

See: https://photonstorm.github.io/phaser3-docs/Phaser.Input.Keyboard.KeyboardPlugin.html
